// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: proto/dhotstuff.proto

// Package dhotstuff defines the wire types and gRPC service for the
// D-HotStuff dynamic-committee BFT consensus protocol.
//
// D-HotStuff extends HotStuff with first-class membership-change support:
//   - Every block carries a batch of MembershipRequests (ADD / REMOVE / REGULAR).
//   - The QuorumCert stores raw per-replica ECDSA signatures together with
//     signer identities so that a verifier does not need a fixed committee map.
//   - conf_number tracks the configuration epoch; view_number tracks the
//     monotone leader-rotation counter within an epoch.

package dhotstuffpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestType classifies a client command carried inside a MembershipRequest.
//
//	REGULAR – ordinary application command; no committee change.
//	ADD     – request to add the identified client to the active committee.
//	REMOVE  – request to remove the identified client from the active committee.
type RequestType int32

const (
	// Default value; represents a normal (non-membership) client command.
	RequestType_REGULAR RequestType = 0
	// Membership-addition request for the identified replica.
	RequestType_ADD RequestType = 1
	// Membership-removal request for the identified replica.
	RequestType_REMOVE RequestType = 2
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "REGULAR",
		1: "ADD",
		2: "REMOVE",
	}
	RequestType_value = map[string]int32{
		"REGULAR": 0,
		"ADD":     1,
		"REMOVE":  2,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dhotstuff_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_proto_dhotstuff_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{0}
}

// MembershipRequest wraps a single client command together with its
// classification so that the consensus layer can route REGULAR commands to the
// application state machine and ADD/REMOVE commands to the membership manager.
type MembershipRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Classifies whether this is a plain command or a committee change.
	Type RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=dhotstuff.RequestType" json:"type,omitempty"`
	// Stable string identity of the originating client (e.g. a public key
	// fingerprint or a human-readable name).
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Opaque, application-level command payload.  For ADD/REMOVE requests this
	// typically encodes the replica's network address and public key material.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipRequest) Reset() {
	*x = MembershipRequest{}
	mi := &file_proto_dhotstuff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipRequest) ProtoMessage() {}

func (x *MembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipRequest.ProtoReflect.Descriptor instead.
func (*MembershipRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{0}
}

func (x *MembershipRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_REGULAR
}

func (x *MembershipRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MembershipRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// QuorumCert is D-HotStuff's quorum certificate.
//
// Unlike the upstream hotstuffpb.QuorumCert (which uses a polymorphic
// QuorumSignature that may be a BLS aggregate), D-HotStuff always stores
// individual raw ECDSA signatures so that membership-change proofs can be
// audited without access to a fixed, pre-shared committee roster.
//
// Fields:
//
//	type        – human-readable label ("generic", "prepare", etc.).
//	view_number – monotone view counter at which the QC was formed.
//	conf_number – configuration epoch under which the QC was formed.
//	block_hash  – SHA-256 hash of the certified block.
//	signatures  – one DER-encoded ECDSA signature per quorum member.
//	signer_ids  – replica IDs corresponding to each entry in `signatures`.
//	              len(signer_ids) == len(signatures) MUST hold.
type QuorumCert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Label distinguishing QC roles in the protocol (e.g. "generic").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// View number at the time the certificate was assembled.
	ViewNumber uint64 `protobuf:"varint,2,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	// Configuration (epoch) number at the time the certificate was assembled.
	ConfNumber uint64 `protobuf:"varint,3,opt,name=conf_number,json=confNumber,proto3" json:"conf_number,omitempty"`
	// SHA-256 digest of the serialised Block this certificate covers.
	BlockHash []byte `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// Raw DER-encoded ECDSA signatures, one per quorum participant.
	Signatures [][]byte `protobuf:"bytes,5,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Stable string replica identifiers aligned with `signatures`.
	SignerIds     []string `protobuf:"bytes,6,rep,name=signer_ids,json=signerIds,proto3" json:"signer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	mi := &file_proto_dhotstuff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCert.ProtoReflect.Descriptor instead.
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{1}
}

func (x *QuorumCert) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QuorumCert) GetViewNumber() uint64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *QuorumCert) GetConfNumber() uint64 {
	if x != nil {
		return x.ConfNumber
	}
	return 0
}

func (x *QuorumCert) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *QuorumCert) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *QuorumCert) GetSignerIds() []string {
	if x != nil {
		return x.SignerIds
	}
	return nil
}

// Block is the unit of replication in D-HotStuff.
//
// It extends the plain HotStuff block with:
//   - A batch of typed MembershipRequests instead of opaque Commands.
//   - conf_number to let replicas detect epoch boundaries.
//   - A D-HotStuff QuorumCert (justify) that carries individual ECDSA sigs.
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 hash of the parent block.  All zeros for the genesis block.
	ParentHash []byte `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	// Ordered list of client requests included in this block.
	Batch []*MembershipRequest `protobuf:"bytes,2,rep,name=batch,proto3" json:"batch,omitempty"`
	// QC over the parent block; the "justify" link in the HotStuff chain.
	Justify *QuorumCert `protobuf:"bytes,3,opt,name=justify,proto3" json:"justify,omitempty"`
	// Chain height (0-indexed; genesis = 0).
	Height uint64 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// Configuration epoch this block was proposed under.
	ConfNumber    uint64 `protobuf:"varint,5,opt,name=conf_number,json=confNumber,proto3" json:"conf_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_dhotstuff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Block) GetBatch() []*MembershipRequest {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *Block) GetJustify() *QuorumCert {
	if x != nil {
		return x.Justify
	}
	return nil
}

func (x *Block) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetConfNumber() uint64 {
	if x != nil {
		return x.ConfNumber
	}
	return 0
}

// NewViewMsg is sent by a replica to the next leader when it advances to a new
// view, carrying the highest generic QC it knows of so that the leader can
// assemble a fresh HighQC.
type NewViewMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// View the sender is advancing *to*.
	ViewNumber uint64 `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	// Configuration epoch of the sender.
	ConfNumber uint64 `protobuf:"varint,2,opt,name=conf_number,json=confNumber,proto3" json:"conf_number,omitempty"`
	// The highest generic QC known to the sender at the time of sending.
	GenericQc     *QuorumCert `protobuf:"bytes,3,opt,name=generic_qc,json=genericQc,proto3" json:"generic_qc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewMsg) Reset() {
	*x = NewViewMsg{}
	mi := &file_proto_dhotstuff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMsg) ProtoMessage() {}

func (x *NewViewMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMsg.ProtoReflect.Descriptor instead.
func (*NewViewMsg) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{3}
}

func (x *NewViewMsg) GetViewNumber() uint64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *NewViewMsg) GetConfNumber() uint64 {
	if x != nil {
		return x.ConfNumber
	}
	return 0
}

func (x *NewViewMsg) GetGenericQc() *QuorumCert {
	if x != nil {
		return x.GenericQc
	}
	return nil
}

// VoteMsg is the vote a replica casts for a proposed block.
//
// The leader collects 2f+1 VoteMsgs and combines their `signature` fields into
// a QuorumCert for the next block's `justify`.
type VoteMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// View in which this vote is cast.
	ViewNumber uint64 `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	// Configuration epoch in which this vote is cast.
	ConfNumber uint64 `protobuf:"varint,2,opt,name=conf_number,json=confNumber,proto3" json:"conf_number,omitempty"`
	// SHA-256 hash of the block being voted on.
	BlockHash []byte `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// DER-encoded ECDSA signature over (view_number || conf_number || block_hash).
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Stable string identity of the signing replica.
	SignerId      string `protobuf:"bytes,5,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteMsg) Reset() {
	*x = VoteMsg{}
	mi := &file_proto_dhotstuff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteMsg) ProtoMessage() {}

func (x *VoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteMsg.ProtoReflect.Descriptor instead.
func (*VoteMsg) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{4}
}

func (x *VoteMsg) GetViewNumber() uint64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *VoteMsg) GetConfNumber() uint64 {
	if x != nil {
		return x.ConfNumber
	}
	return 0
}

func (x *VoteMsg) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *VoteMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VoteMsg) GetSignerId() string {
	if x != nil {
		return x.SignerId
	}
	return ""
}

// UpdateRequest is sent by a replica that needs to synchronise with the
// current leader (e.g. after a restart or a membership-add event).
type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the replica requesting the update.
	ReplicaId     string `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_dhotstuff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

// UpdateResponse carries the highest committed block known to the responder,
// allowing the requester to fast-forward its local state.
type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The best (highest committed) block the responder is aware of.
	BestBlock     *Block `protobuf:"bytes,1,opt,name=best_block,json=bestBlock,proto3" json:"best_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_dhotstuff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetBestBlock() *Block {
	if x != nil {
		return x.BestBlock
	}
	return nil
}

// HistoryRequest is sent by a replica that needs the full committed chain,
// typically after being added to the committee as a new member.
type HistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the replica requesting history.
	ReplicaId     string `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_dhotstuff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{7}
}

func (x *HistoryRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

// HistoryResponse delivers an ordered sequence of committed blocks,
// oldest-first, so that the requester can replay them and reconstruct state.
type HistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Committed blocks in ascending height order (genesis block first).
	History       []*Block `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_dhotstuff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhotstuff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_dhotstuff_proto_rawDescGZIP(), []int{8}
}

func (x *HistoryResponse) GetHistory() []*Block {
	if x != nil {
		return x.History
	}
	return nil
}

var File_proto_dhotstuff_proto protoreflect.FileDescriptor

const file_proto_dhotstuff_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dhotstuff.proto\x12\tdhotstuff\x1a\x1bgoogle/protobuf/empty.proto\"v\n" +
	"\x11MembershipRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.dhotstuff.RequestTypeR\x04type\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xc0\x01\n" +
	"\n" +
	"QuorumCert\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vview_number\x18\x02 \x01(\x04R\n" +
	"viewNumber\x12\x1f\n" +
	"\vconf_number\x18\x03 \x01(\x04R\n" +
	"confNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12\x1e\n" +
	"\n" +
	"signatures\x18\x05 \x03(\fR\n" +
	"signatures\x12\x1d\n" +
	"\n" +
	"signer_ids\x18\x06 \x03(\tR\tsignerIds\"\xc6\x01\n" +
	"\x05Block\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x122\n" +
	"\x05batch\x18\x02 \x03(\v2\x1c.dhotstuff.MembershipRequestR\x05batch\x12/\n" +
	"\ajustify\x18\x03 \x01(\v2\x15.dhotstuff.QuorumCertR\ajustify\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x04R\x06height\x12\x1f\n" +
	"\vconf_number\x18\x05 \x01(\x04R\n" +
	"confNumber\"\x84\x01\n" +
	"\n" +
	"NewViewMsg\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x04R\n" +
	"viewNumber\x12\x1f\n" +
	"\vconf_number\x18\x02 \x01(\x04R\n" +
	"confNumber\x124\n" +
	"\n" +
	"generic_qc\x18\x03 \x01(\v2\x15.dhotstuff.QuorumCertR\tgenericQc\"\xa5\x01\n" +
	"\aVoteMsg\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x04R\n" +
	"viewNumber\x12\x1f\n" +
	"\vconf_number\x18\x02 \x01(\x04R\n" +
	"confNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fR\tblockHash\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigner_id\x18\x05 \x01(\tR\bsignerId\".\n" +
	"\rUpdateRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\"A\n" +
	"\x0eUpdateResponse\x12/\n" +
	"\n" +
	"best_block\x18\x01 \x01(\v2\x10.dhotstuff.BlockR\tbestBlock\"/\n" +
	"\x0eHistoryRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\"=\n" +
	"\x0fHistoryResponse\x12*\n" +
	"\ahistory\x18\x01 \x03(\v2\x10.dhotstuff.BlockR\ahistory*/\n" +
	"\vRequestType\x12\v\n" +
	"\aREGULAR\x10\x00\x12\a\n" +
	"\x03ADD\x10\x01\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x022\x89\x02\n" +
	"\tDHotStuff\x12/\n" +
	"\aPropose\x12\x10.dhotstuff.Block\x1a\x12.dhotstuff.VoteMsg\x12<\n" +
	"\vSendNewView\x12\x15.dhotstuff.NewViewMsg\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\rRequestUpdate\x12\x18.dhotstuff.UpdateRequest\x1a\x19.dhotstuff.UpdateResponse\x12G\n" +
	"\x0eRequestHistory\x12\x19.dhotstuff.HistoryRequest\x1a\x1a.dhotstuff.HistoryResponseB<Z:github.com/prathmesh-d-glitch/d-hotstuff/proto/dhotstuffpbb\x06proto3"

var (
	file_proto_dhotstuff_proto_rawDescOnce sync.Once
	file_proto_dhotstuff_proto_rawDescData []byte
)

func file_proto_dhotstuff_proto_rawDescGZIP() []byte {
	file_proto_dhotstuff_proto_rawDescOnce.Do(func() {
		file_proto_dhotstuff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dhotstuff_proto_rawDesc), len(file_proto_dhotstuff_proto_rawDesc)))
	})
	return file_proto_dhotstuff_proto_rawDescData
}

var file_proto_dhotstuff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dhotstuff_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_dhotstuff_proto_goTypes = []any{
	(RequestType)(0),          // 0: dhotstuff.RequestType
	(*MembershipRequest)(nil), // 1: dhotstuff.MembershipRequest
	(*QuorumCert)(nil),        // 2: dhotstuff.QuorumCert
	(*Block)(nil),             // 3: dhotstuff.Block
	(*NewViewMsg)(nil),        // 4: dhotstuff.NewViewMsg
	(*VoteMsg)(nil),           // 5: dhotstuff.VoteMsg
	(*UpdateRequest)(nil),     // 6: dhotstuff.UpdateRequest
	(*UpdateResponse)(nil),    // 7: dhotstuff.UpdateResponse
	(*HistoryRequest)(nil),    // 8: dhotstuff.HistoryRequest
	(*HistoryResponse)(nil),   // 9: dhotstuff.HistoryResponse
	(*emptypb.Empty)(nil),     // 10: google.protobuf.Empty
}
var file_proto_dhotstuff_proto_depIdxs = []int32{
	0,  // 0: dhotstuff.MembershipRequest.type:type_name -> dhotstuff.RequestType
	1,  // 1: dhotstuff.Block.batch:type_name -> dhotstuff.MembershipRequest
	2,  // 2: dhotstuff.Block.justify:type_name -> dhotstuff.QuorumCert
	2,  // 3: dhotstuff.NewViewMsg.generic_qc:type_name -> dhotstuff.QuorumCert
	3,  // 4: dhotstuff.UpdateResponse.best_block:type_name -> dhotstuff.Block
	3,  // 5: dhotstuff.HistoryResponse.history:type_name -> dhotstuff.Block
	3,  // 6: dhotstuff.DHotStuff.Propose:input_type -> dhotstuff.Block
	4,  // 7: dhotstuff.DHotStuff.SendNewView:input_type -> dhotstuff.NewViewMsg
	6,  // 8: dhotstuff.DHotStuff.RequestUpdate:input_type -> dhotstuff.UpdateRequest
	8,  // 9: dhotstuff.DHotStuff.RequestHistory:input_type -> dhotstuff.HistoryRequest
	5,  // 10: dhotstuff.DHotStuff.Propose:output_type -> dhotstuff.VoteMsg
	10, // 11: dhotstuff.DHotStuff.SendNewView:output_type -> google.protobuf.Empty
	7,  // 12: dhotstuff.DHotStuff.RequestUpdate:output_type -> dhotstuff.UpdateResponse
	9,  // 13: dhotstuff.DHotStuff.RequestHistory:output_type -> dhotstuff.HistoryResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_dhotstuff_proto_init() }
func file_proto_dhotstuff_proto_init() {
	if File_proto_dhotstuff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dhotstuff_proto_rawDesc), len(file_proto_dhotstuff_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dhotstuff_proto_goTypes,
		DependencyIndexes: file_proto_dhotstuff_proto_depIdxs,
		EnumInfos:         file_proto_dhotstuff_proto_enumTypes,
		MessageInfos:      file_proto_dhotstuff_proto_msgTypes,
	}.Build()
	File_proto_dhotstuff_proto = out.File
	file_proto_dhotstuff_proto_goTypes = nil
	file_proto_dhotstuff_proto_depIdxs = nil
}
