// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.4
// source: proto/dhotstuff.proto

// Package dhotstuff defines the wire types and gRPC service for the
// D-HotStuff dynamic-committee BFT consensus protocol.
//
// D-HotStuff extends HotStuff with first-class membership-change support:
//   - Every block carries a batch of MembershipRequests (ADD / REMOVE / REGULAR).
//   - The QuorumCert stores raw per-replica ECDSA signatures together with
//     signer identities so that a verifier does not need a fixed committee map.
//   - conf_number tracks the configuration epoch; view_number tracks the
//     monotone leader-rotation counter within an epoch.

package dhotstuffpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DHotStuff_Propose_FullMethodName        = "/dhotstuff.DHotStuff/Propose"
	DHotStuff_SendNewView_FullMethodName    = "/dhotstuff.DHotStuff/SendNewView"
	DHotStuff_RequestUpdate_FullMethodName  = "/dhotstuff.DHotStuff/RequestUpdate"
	DHotStuff_RequestHistory_FullMethodName = "/dhotstuff.DHotStuff/RequestHistory"
)

// DHotStuffClient is the client API for DHotStuff service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DHotStuff is the peer-to-peer RPC surface of the D-HotStuff protocol.
//
// All four RPCs are point-to-point (unicast); multicast is handled at the
// caller level (e.g. gorums or a simple fan-out loop).
type DHotStuffClient interface {
	// Propose is called by the current leader to send a new Block to a replica.
	// The replica validates the block and, if acceptable, returns a signed
	// VoteMsg.  On failure the replica SHOULD return a gRPC status error rather
	// than an empty vote.
	Propose(ctx context.Context, in *Block, opts ...grpc.CallOption) (*VoteMsg, error)
	// SendNewView is called by a replica to deliver a NewViewMsg to the next
	// leader.  The leader collects these messages to determine HighQC.
	// Returns google.protobuf.Empty on success.
	SendNewView(ctx context.Context, in *NewViewMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RequestUpdate is called by a replica that needs to learn the current
	// best-committed block from a peer (lightweight catch-up).
	RequestUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// RequestHistory is called by a newly added (or recovering) replica to
	// download the full committed chain from a peer.
	RequestHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
}

type dHotStuffClient struct {
	cc grpc.ClientConnInterface
}

func NewDHotStuffClient(cc grpc.ClientConnInterface) DHotStuffClient {
	return &dHotStuffClient{cc}
}

func (c *dHotStuffClient) Propose(ctx context.Context, in *Block, opts ...grpc.CallOption) (*VoteMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteMsg)
	err := c.cc.Invoke(ctx, DHotStuff_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHotStuffClient) SendNewView(ctx context.Context, in *NewViewMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DHotStuff_SendNewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHotStuffClient) RequestUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, DHotStuff_RequestUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHotStuffClient) RequestHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, DHotStuff_RequestHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DHotStuffServer is the server API for DHotStuff service.
// All implementations must embed UnimplementedDHotStuffServer
// for forward compatibility.
//
// DHotStuff is the peer-to-peer RPC surface of the D-HotStuff protocol.
//
// All four RPCs are point-to-point (unicast); multicast is handled at the
// caller level (e.g. gorums or a simple fan-out loop).
type DHotStuffServer interface {
	// Propose is called by the current leader to send a new Block to a replica.
	// The replica validates the block and, if acceptable, returns a signed
	// VoteMsg.  On failure the replica SHOULD return a gRPC status error rather
	// than an empty vote.
	Propose(context.Context, *Block) (*VoteMsg, error)
	// SendNewView is called by a replica to deliver a NewViewMsg to the next
	// leader.  The leader collects these messages to determine HighQC.
	// Returns google.protobuf.Empty on success.
	SendNewView(context.Context, *NewViewMsg) (*emptypb.Empty, error)
	// RequestUpdate is called by a replica that needs to learn the current
	// best-committed block from a peer (lightweight catch-up).
	RequestUpdate(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// RequestHistory is called by a newly added (or recovering) replica to
	// download the full committed chain from a peer.
	RequestHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	mustEmbedUnimplementedDHotStuffServer()
}

// UnimplementedDHotStuffServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDHotStuffServer struct{}

func (UnimplementedDHotStuffServer) Propose(context.Context, *Block) (*VoteMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedDHotStuffServer) SendNewView(context.Context, *NewViewMsg) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNewView not implemented")
}
func (UnimplementedDHotStuffServer) RequestUpdate(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestUpdate not implemented")
}
func (UnimplementedDHotStuffServer) RequestHistory(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestHistory not implemented")
}
func (UnimplementedDHotStuffServer) mustEmbedUnimplementedDHotStuffServer() {}
func (UnimplementedDHotStuffServer) testEmbeddedByValue()                   {}

// UnsafeDHotStuffServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DHotStuffServer will
// result in compilation errors.
type UnsafeDHotStuffServer interface {
	mustEmbedUnimplementedDHotStuffServer()
}

func RegisterDHotStuffServer(s grpc.ServiceRegistrar, srv DHotStuffServer) {
	// If the following call panics, it indicates UnimplementedDHotStuffServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DHotStuff_ServiceDesc, srv)
}

func _DHotStuff_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHotStuffServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHotStuff_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHotStuffServer).Propose(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHotStuff_SendNewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHotStuffServer).SendNewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHotStuff_SendNewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHotStuffServer).SendNewView(ctx, req.(*NewViewMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHotStuff_RequestUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHotStuffServer).RequestUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHotStuff_RequestUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHotStuffServer).RequestUpdate(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHotStuff_RequestHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHotStuffServer).RequestHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHotStuff_RequestHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHotStuffServer).RequestHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DHotStuff_ServiceDesc is the grpc.ServiceDesc for DHotStuff service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DHotStuff_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dhotstuff.DHotStuff",
	HandlerType: (*DHotStuffServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _DHotStuff_Propose_Handler,
		},
		{
			MethodName: "SendNewView",
			Handler:    _DHotStuff_SendNewView_Handler,
		},
		{
			MethodName: "RequestUpdate",
			Handler:    _DHotStuff_RequestUpdate_Handler,
		},
		{
			MethodName: "RequestHistory",
			Handler:    _DHotStuff_RequestHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dhotstuff.proto",
}
